travis:
  secure:
    BINSTAR_TOKEN: h18Jrt0bKJkbR+q/66nFrVa1emI4CmsdBl+totm8Ik377q9qC8KpWXbiD8cMPMzSxfTIKbZVjav80GVBMdCLGinWPSd5iS6VFWg3NQ+TNBDoGhH7WEFMK9NzZqlyhj/tgbeERi9luQ0vdgT1SJIkW4WsS/5IPJ8rwrosejavg7ffdmmStxGM60DqeSo6NhnrSnS6CU/a5RqDEHbCq2K7aYTY7EcdmMcMrAYlZs3yFZBpSFhl5PbLo8+aS78t3mM4rstQVoPoOhsT5+P71/Z/1sVHU5cIUPyr2Ub6f6q7loB4FTT4KtqJyZtrpFdFVjs/apnLVRowon2N7k8so3O1v4LJAZ58vBAkmNEtydUZGrEjmdSQNKQusd1nuggE3PaYWVw/A9UercgH1f3IB5gKNFGZjJZI/4qCxQKrnIpLBpY5LqTSmzfJ+gwM51TIwnUKzHaZCmbEMXL6cbYAxO4hT/7Klr/YWqWcYqa/ptT5v5TJHfzFd0t3WBy0rXi00qYRJYSUK3VSnOrIdAjU1/RRiP8Ul98mTLThX/2V0OMBix/K0h54+/28rn8GMzFwGHW9LICGmRSdHBQ6OLElm1kpDu5hpL6eAK0B5uInXlBK9yJXSYtRGs2fKx/FNMJvjZkzkRpOvDxQpvwawpNpKUn4oZgTsSiZGs3KNLbraIHxlWY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
