travis:
  secure:
    BINSTAR_TOKEN: jbySTaC5MFjdNawxGWe1MRQnp2MNo8j0GSDjiaP/AEBSMPiuMOXjG9WRBI0mPe9vxVL+BMWgRudKPzFoJkAD9xGi4IFylgX7MQhiLBtYKlntqS0z1MLfEJDXeAT2IgMOatystdyL6akiY7jFWfNaPfQNsEvHdipWdw9j25oKY5v3WGhnjf2Q36kdWBtb5r8d9baUwxGL3lijhLsYdJlj/w95Q7Lz8l2VhrCGyfS95GIDOJ8qu5pObH43tjy0NrkQQCJbe663aJ8z1du3MjJgV2TDY2OvVQq0+N8KSEW/PYVPC1siMktJpN+x2+bMj1//qBHmFvrL1JsHf8gYLmibh6vE7gyj0W79ZdIMLOJt9nEGdlp4uPvcn2fYBTJMwTKJj9Qr6n0K5MNjf9cdra3KBLQjhlvLD7zZouOlOjHbOOpLRc7kGCxiEZ1pUNTVV1mjLHz/AnKJ3+a/b64quo8yOe7V5Rq+NeNL8LWH6JBpevhXWKxs1nTxwaWlzYOb7TpPjft00Ge0QmkHUy3fQWMKP/JDbtjcHiDH3bIwxN5Lj4pFmh6Nyb8Nb3z1Fv0tIoZCs3RkzdCc1JzMSbOHaq/ss44zeXya9klOMwWaDZF5+bwSKnCjHq+hXGJ0SLix2hVdj7bZs23jSuC8rw3BMyhSHQB4JTiR6e4ubuPnlAhldtA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
