travis:
  secure:
    BINSTAR_TOKEN: Cj2PZHipNuabGLnGN4tuamVYqUyedEQm2F/JPGf5JlOUM76id90Wie6DKFvstfHLpfvXAAJG00g9JGcOy9E0aGiLcjmB/C9q8ERJRVvXyWep93EYGTY2xNhazfkDNqeckkC/vlDM3E9LKNuCHYLdhmRabEbKTBFa94XmS6gzSguwAG+E6ULYnG2KiT5PhB1nbTFhJCkXXORtQXafP6W+ZBwn+J+ftdJ+E1+EhamhScjNOQ86hZDGxK8yiifWuPY+6slnK/KIFGmByxBEt9MEhyAJUM+X0XWDmanFrhWD4zGiUUPW49BWwFrnB5wbYRAVYUTf3IbUtSpO5KwVvCzJjQ0Fz4cHSckTh3+CIzujQiEFzMqVvtoi4h3+wozd7DIn+fsndBnGbD8cCYOxmUOpU+K1f41CBQRkQcNAZTbgULIhKjofnxjKcn2g0MoMo8DU2rZlkSHI0l6ykF/66n/CyxgzrQYJ1IodVA0/7E2ACnRAM+CHEK2wyBLoe5q6XhXYzYKEByit36d96LDhgSJRaRFsQd5iVvXZ3liCi6KsgQzJMCdD84gV6iO+0GuWefkN8ND/pxMi1E6YLP9g1A8aFP/TETuQqxmorHyPVN43xrXcwjb1u/7rsy/gSUkmGT4UV3V7ZF2aZfn6eOZX1ZvDywlwfgo8l/ghUyLXpOtQ6o4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
